id: aef7ef7ab4d04fb68485a1c9e923523e
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_558-Destroyer_of_the_Great_Trichiliocosm-v1
  language: en
  author: ''
  volume: {}
